// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddShare() {
  return window['go']['main']['App']['AddShare']();
}

export function CodeLogin(arg1) {
  return window['go']['main']['App']['CodeLogin'](arg1);
}

export function DelHistory(arg1) {
  return window['go']['main']['App']['DelHistory'](arg1);
}

export function DelShare(arg1) {
  return window['go']['main']['App']['DelShare'](arg1);
}

export function DownLoad(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownLoad'](arg1, arg2, arg3);
}

export function DownLoadTaskStop(arg1) {
  return window['go']['main']['App']['DownLoadTaskStop'](arg1);
}

export function EditHostName(arg1) {
  return window['go']['main']['App']['EditHostName'](arg1);
}

export function EditShare(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditShare'](arg1, arg2, arg3);
}

export function GetHistoryList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetHistoryList'](arg1, arg2, arg3, arg4, arg5);
}

export function GetHostList(arg1) {
  return window['go']['main']['App']['GetHostList'](arg1);
}

export function GetHostShareList(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetHostShareList'](arg1, arg2, arg3, arg4);
}

export function GetHttpSign() {
  return window['go']['main']['App']['GetHttpSign']();
}

export function GetLocalInfo() {
  return window['go']['main']['App']['GetLocalInfo']();
}

export function GetLocalIp() {
  return window['go']['main']['App']['GetLocalIp']();
}

export function GetShareExt(arg1) {
  return window['go']['main']['App']['GetShareExt'](arg1);
}

export function GetShareList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetShareList'](arg1, arg2, arg3, arg4, arg5);
}

export function Init() {
  return window['go']['main']['App']['Init']();
}

export function OpenDir(arg1, arg2) {
  return window['go']['main']['App']['OpenDir'](arg1, arg2);
}

export function OpenFile(arg1, arg2) {
  return window['go']['main']['App']['OpenFile'](arg1, arg2);
}

export function SyncHost() {
  return window['go']['main']['App']['SyncHost']();
}

export function SyncHostShare(arg1) {
  return window['go']['main']['App']['SyncHostShare'](arg1);
}
