// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function AddShare():Promise<void>;

export function CodeLogin(arg1:string):Promise<string>;

export function DelHistory(arg1:Array<string>):Promise<void>;

export function DelShare(arg1:Array<string>):Promise<void>;

export function DownLoad(arg1:common.DownLoadHistory,arg2:string,arg3:string):Promise<common.DownLoadHistory>;

export function DownLoadTaskStop(arg1:number):Promise<void>;

export function EditHostName(arg1:string):Promise<void>;

export function EditShare(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetHistoryList(arg1:string,arg2:Array<string>,arg3:number,arg4:number,arg5:number):Promise<common.DownLoadHistoryList>;

export function GetHostList(arg1:string):Promise<Array<{[key: string]: string}>>;

export function GetHostShareList(arg1:string,arg2:Array<string>,arg3:number,arg4:number):Promise<common.DownLoadHistoryList>;

export function GetHttpSign():Promise<{[key: string]: string}>;

export function GetLocalInfo():Promise<{[key: string]: string}>;

export function GetLocalIp():Promise<string>;

export function GetShareExt(arg1:string):Promise<Array<string>>;

export function GetShareList(arg1:string,arg2:string,arg3:Array<string>,arg4:number,arg5:number):Promise<common.DownLoadHistoryList>;

export function Init():Promise<{[key: string]: string}>;

export function OpenDir(arg1:number,arg2:string):Promise<void>;

export function OpenFile(arg1:number,arg2:string):Promise<void>;

export function SyncHost():Promise<void>;

export function SyncHostShare(arg1:string):Promise<void>;
